<a href="https://colab.research.google.com/github/agarh16/TF_T/blob/main/TF_Tutorial_TechwithTim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


How to create some tensors.

In [ ]:
string = tf.Variable("Hello World", tf.string)
number = tf.Variable(123, tf.int16)
floating = tf.Variable(3.1416, tf.float64)

# Rank/Degree of Tensors.

The Rank or Degree refers to the number of dimensions involved in the tensor. Tensors of Rank 0 are called a *scalar*.

In [ ]:
rank1_tensor = tf.Variable(["Hello", "Ok", "Andrea"], tf.string)
rank2_tensor = tf.Variable([["Hallo", "Okay","hi"], ["test", "yes", "ok"]], tf.string)

To determine the rank of a tensor we can call the following method.

In [ ]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#Shape of a Tensor
The shape of a tensor is the amount of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but it is sometimes unknown.

TensorFlow can't convert non-square to tensor.

In [ ]:
rank2_tensor.shape

TensorShape([2, 3])

#Changing Shape of a Tensor
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convenient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [ ]:
tensor_one = tf.ones([1,2,3]) #tensorflow creates a shape of [1,2,3] tensor full of ones
tensor_two = tf.reshape(tensor_one, [2,3,1])
tensor_three = tf.reshape(tensor_one, [3,-1]) #tells the tensor to calculate the size of the dimension in that place
tensor_four = tf.ones([2,2,2,6])

Printing the tensors.

In [ ]:
print(tensor_one)
print(tensor_two)
print(tensor_three)
print(tensor_four)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]], shape=(2, 2, 2, 6), dtype=float32)


# Types of Tensors

*   Variable
*   Constant
*   Placeholder
*   SparseTensor

All except variables may be immutable.



# Evaluating Tensors
It might happen that you need to get a value of a tensor. Since tensors represent a partially complete computation we will sometimes need to run a *session* to evaluate it.

In [ ]:
"""with tf.Session() as sess: #creates a session using the default graph
tensor.eval()"""

'with tf.Session as sess: #creates a session using the default graph\ntensor.eval()'